### ISSUE TITLE
[Bug] Timer

### ISSUE THREAD

**Issue by SethCalkins** [adamtheray/TimeTru#43]
## Selecting the Checkmark on a timer with the Finish Ticket Slider in the "Off" Position Still closes out the ticket.

Steps to reproduce: 

1. Create a new ticket with "Start Timer" On
2. Go To Timers
3. Stop Timer 
4. Verify "Finish Ticket Slider" is in Off Position
5. Enter in Ticket Details
6. Click Red Check Mark on Timer

### Notice Ticket will no longer be in "My Tickets"

**Comment by adamtheray** [comment]
Fixed in latest dev.
